@startuml

[ANTLR4] as antlr4 #LightSteelBlue
[flat\nassembler] as flat #LightSteelBlue
[JCC] as jcc
[JCommander] as jcommander #LightSteelBlue

jcommander <. jcc : use
antlr4 <. jcc : use
jcc .> flat : use

@enduml
