@startuml

[jcc-base] as base
[jcc-antlr4] as antlr4
[jcc-assembunny] as assembunny
[jcc-basic] as basic
[jcc-tiny] as tiny
[jcc-compiler] as compiler

base <.u. antlr4
base <.u. assembunny
base <.u. basic
base <.u. tiny
base <.u. compiler
antlr4 <.u. assembunny
antlr4 <.u. basic
antlr4 <.u. tiny
assembunny <.u. compiler
basic <.u. compiler
tiny <.u. compiler

@enduml
