#!/bin/bash

SCRIPT="$0"
if [[ -L "$SCRIPT" ]]; then
  # Resolve link to find script
  SCRIPT=$(realpath "$SCRIPT")
fi
SCRIPT_DIR=$(dirname -- "$SCRIPT")

JCC_LIB="$SCRIPT_DIR/../lib"
JCC_JAR="$JCC_LIB/jcc-compiler-${project.version}.jar"

if [[ -n "$JAVA_HOME" && -f "$JAVA_HOME/bin/java" ]]; then
  JAVA_CMD="$JAVA_HOME/bin/java"
else
  JAVA_CMD=java
fi

"$JAVA_CMD" -jar "$JCC_JAR" $*
