name: windows build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Clang 18
        uses: egor-tensin/setup-clang@v1
        with:
          version: 18
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B verify -P llvm-tests --file pom.xml
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-artifacts
          path: jcc-compiler/target/jcc-*.zip
